### ISSUE TITLE
can't resolve fs

### ISSUE THREAD

**Issue by dcrystalj** [PageProofCom/azure-functions-webpack-plugin#1]
When I run webpack with this package I get error

```
ERROR in ./node_modules/strtok3/lib/FsPromise.js
Module not found: Error: Can't resolve 'fs' in '/home/../node_modules/strtok3/lib'
 @ ./node_modules/strtok3/lib/FsPromise.js 6:11-24
 @ ./node_modules/strtok3/lib/index.js
 @ ./node_modules/file-type/index.js
 @ ./src/MyFunction/index.js
 @ ./src/index.js
```

**Comment by jmshal** [comment]
Could you please provide your webpack.config.js file?

Alternatively, if you haven't already done so, you may need to set the `target` webpack config option to `"node"`, like so;

```js
module.exports = {
  target: 'node',
  plugins: [
    new AzureFunctionsWebpackPlugin(),
  ],
};
```

I believe that should prevent webpack from trying to resolve `fs` (and other Node.js built-in modules).

**Comment by dcrystalj** [comment]
This fixed the problem. 
now I get only a warning which i believe is ok

```
WARNING in ./node_modules/debug/src/node.js
Module not found: Error: Can't resolve 'supports-color' in '/home/.../node_modules/debug/src'
 @ ./node_modules/debug/src/node.js
 @ ./node_modules/debug/src/index.js
 @ ./node_modules/strtok3/lib/ReadStreamTokenizer.js
 @ ./node_modules/strtok3/lib/core.js
 @ ./node_modules/file-type/core.js
 @ ./node_modules/file-type/index.js
 @ ./src/BlobTrigger/index.js
 @ ./src/index.js

```

But when I add dist folder to project in visual studio code I cannot deploy bundled functions.
I get this error:
![image](https://user-images.githubusercontent.com/1460727/74384246-2a476300-4df1-11ea-9c6a-27d62421c9ec.png)
Internal error: Expected value to be neither null, undefined, nor empty: projectRuntime

**Comment by jmshal** [comment]
~Do you get any additional information from that "internal error"? Like a stacktrace? I don't recognise that error message, so I can't grasp whether it's related to this plugin or something else? Any additional information is welcome, I'll happily take a look.~

I take it back, it looks like this might explain the error: https://github.com/microsoft/vscode-azurefunctions/wiki/Project-Runtime

**Comment by jmshal** [comment]
Let me know if you need anything else, I'm closing this because the original issue has been resolved, and I'm fairly sure the new issue you're experiencing is unrelated to this plugin.

**Comment by dcrystalj** [comment]
I can confirm this warning happens always and is unrelated. The problem is with visual studio code plugin which expects .vscode folder with settings within dist folder. If run `webpack --mode production && cp -r .vscode dist/`

Howerver I have another issue with using Jimp external library. See #2
